### ISSUE TITLE
Immediately crashes in release build for Samsung Galaxy Z Flip3 5G

### ISSUE THREAD

**Issue by nicodumdum** [MisterJimson/multi_screen_layout#18]

**Comment by nicodumdum** [comment]
Sorry, I accidentally pressed ENTER while typing the title and the issue immediately posted. I immediately panicked and thought of deleting and writing a new issue but what the heck. LOL.

Hi, 

I was trying to make this plugin work for my Samsung Galaxy Z Flip3 5G. It works fine and detects the Flex Mode properly in DEBUG mode. However, when I try to run in RELEASE mode it immediately crashes upon starting the app.

Here's the error message that appeared in the debug console:
<details>
<summary>Debug Console</summary>

```txt
√  Built build\app\outputs\flutter-apk\app-release.apk (36.2MB).
W/FlutterActivityAndFragmentDelegate(18038): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
E/AndroidRuntime(18038): FATAL EXCEPTION: main
E/AndroidRuntime(18038): Process: com.example.flutter_application_2, PID: 18038
E/AndroidRuntime(18038): java.lang.AbstractMethodError: abstract method "void androidx.window.sidecar.SidecarInterface$SidecarCallback.onDeviceStateChanged(androidx.window.sidecar.SidecarDeviceState)"
E/AndroidRuntime(18038): 	at androidx.window.sidecar.SamsungSidecarImpl.updateDevicePosture(SamsungSidecarImpl.java:85)
E/AndroidRuntime(18038): 	at androidx.window.sidecar.SamsungSidecarImpl.access$000(SamsungSidecarImpl.java:44)
E/AndroidRuntime(18038): 	at androidx.window.sidecar.SamsungSidecarImpl$SamsungSidecarCallbackListener.onDeviceStateChanged(SamsungSidecarImpl.java:62)
E/AndroidRuntime(18038): 	at android.view.-$$Lambda$5NelMm5rLKQbeBRvtLr6OjxYQ74.run(Unknown Source:2)
E/AndroidRuntime(18038): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(18038): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(18038): 	at android.os.Looper.loop(Looper.java:247)
E/AndroidRuntime(18038): 	at android.app.ActivityThread.main(ActivityThread.java:8656)
E/AndroidRuntime(18038): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18038): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(18038): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Application finished.
Exited (sigterm)
```

</details>

<details>
<summary>flutter doctor -v</summary>

```txt
PS D:\Nico\PRJ\github prj\flutter_qc_qcitizen> flutter doctor -v
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1348], locale en-PH)
    • Flutter version 2.5.3 at C:\Users\Nico\fvm\default
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Nico\sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Nico\sdk
    • Java binary at: C:\Users\Nico\AppData\Local\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Users\Nico\AppData\Local\Android\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\Nico\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (1 available)
    • SM F711B (mobile) • R5CR9144NZL • android-arm64 • Android 11 (API 30)

• No issues found!
```

</details>

<details>
<summary>main.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:multi_screen_layout/multi_screen_layout.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final Orientation orientation = MediaQuery.of(context).orientation;

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SafeArea(
        child: MultiScreenInfo(builder: (info) {
          if (orientation == Orientation.portrait &&
              info.foldDirection == FoldDirection.vertical &&
              info.foldingState == FoldingState.halfOpened) {
            return Column(
              children: [
                Expanded(child: Container(color: Colors.red)),
                Expanded(child: Container(color: Colors.blue)),
              ],
            );
          } else {
            return Column(
              children: [
                Expanded(child: Container(color: Colors.red)),
              ],
            );
          }
        }),
      ),
    );
  }
}
```

</details>

</details>

<details>
<summary>app/build.gradle</summary>

```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutter_application_2"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

</details>

**Comment by MisterJimson** [comment]
Can you try adding:

```
dependencies { implementation "androidx.window:window:1.0.0-beta04" }
```

To your build.gradle and testing again?

**Comment by nicodumdum** [comment]
When I tried to add the implementation in the build.gradle here's the build error

```txt
Launching lib\main.dart on SM F711B in release mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkReleaseAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.window:window:1.0.0-beta04.
     AAR metadata file: C:\Users\Nico\.gradle\caches\transforms-2\files-2.1\a78fdf90e4c1f8464b19895cfb365f3f\jetified-window-1.0.0-beta04\META-INF\com\android\build\gradle\aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 3s
Exception: Gradle task assembleRelease failed with exit code 1
Exited (sigterm)
```

Then when I tried changing the values for `compileSdkVersion` and `targetSdkVersion` to 31 here's the error:
```
Launching lib\main.dart on SM F711B in release mode...
e: C:/Users/Nico/.gradle/caches/transforms-2/files-2.1/06445d7ee3d674db365da5b7e383aeec/jetified-window-1.0.0-beta04-api.jar!/META-INF/window_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: C:/Users/Nico/.gradle/caches/transforms-2/files-2.1/185d46b6321985f52dcc07c04b9e0199/jetified-kotlin-stdlib-common-1.5.31.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: C:/Users/Nico/.gradle/caches/transforms-2/files-2.1/57fff25d753f492b2e9dfa8a7a25a127/jetified-kotlin-stdlib-jdk7-1.5.30.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: C:/Users/Nico/.gradle/caches/transforms-2/files-2.1/7ed1fc227d449123990dfe95b91bbf13/jetified-kotlin-stdlib-1.5.31.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: C:/Users/Nico/.gradle/caches/transforms-2/files-2.1/989d7c521cad3a1e2e82ee6a7a836f54/jetified-kotlinx-coroutines-android-1.5.2.jar!/META-INF/kotlinx-coroutines-android.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: C:/Users/Nico/.gradle/caches/transforms-2/files-2.1/cdd51607f1d98bcc689bce197d763afe/jetified-kotlin-stdlib-jdk8-1.5.30.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: C:/Users/Nico/.gradle/caches/transforms-2/files-2.1/ced2a85cd1d4e10ca7b42bb11579f9f7/jetified-kotlinx-coroutines-core-jvm-1.5.2.jar!/META-INF/kotlinx-coroutines-core.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseKotlin'.
> Compilation error. See log for more details
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 45s
Exception: Gradle task assembleRelease failed with exit code 1
Exited (sigterm)
```

<details>
<summary>app/build.gradle</summary>

```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 31

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutter_application_2"
        minSdkVersion 21
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "androidx.window:window:1.0.0-beta04"
}
```

</details>

**Comment by MisterJimson** [comment]
Hmm. Looks like we may need to have matching kotlin versions?

```
: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
```

What is the kotlin version in your build.gradle? Can you try matching it to the above?

**Comment by nicodumdum** [comment]
I changed it to `ext.kotlin_version = '1.6.0'` in `build.grade` and it ran in both DEBUG and RELEASE mode. Unfortunately, it seemed like it lost all the folding detection. When I fold the device, it is not triggering a widget rebuild. And when I check the locals on app start, it doesn't seem to detect my phone as a foldable device.
![Screenshot 2021-12-08 135050](https://user-images.githubusercontent.com/1650987/145155857-ca92d142-89ee-471c-8535-3e07158f198e.png)

**Comment by MisterJimson** [comment]
Can you retest with version 3.1 and include the Android deps as now noted in the readme?

**Comment by MisterJimson** [comment]
Without more details I will close. Reopen if the issue persists on 3.1.
